// Writes brand/logo.svg (full mark) and brand/logo-mono.svg (one-colour
// silhouette for the macOS menu bar) from the shared tear outline.
//   node brand/build-logo.mjs
import { execFileSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const tear = execFileSync(process.execPath, [join(here, 'tear.mjs')]).toString().trim();

const logo = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024">
  <!-- RIFT: a dark tile torn open; light from the other side pours through.
       Generated by brand/build-logo.mjs from brand/tear.mjs. -->
  <defs>
    <linearGradient id="light" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#FFE27A"/>
      <stop offset="0.45" stop-color="#FF8A3D"/>
      <stop offset="1" stop-color="#FF3D7F"/>
    </linearGradient>
    <linearGradient id="slab" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0" stop-color="#2C2236"/>
      <stop offset="1" stop-color="#100B15"/>
    </linearGradient>
    <radialGradient id="spill" cx="0.5" cy="0.5" r="0.5">
      <stop offset="0" stop-color="#FF7A3D" stop-opacity="0.5"/>
      <stop offset="1" stop-color="#FF7A3D" stop-opacity="0"/>
    </radialGradient>
    <filter id="bloom" x="-80%" y="-10%" width="260%" height="120%">
      <feGaussianBlur stdDeviation="26"/>
    </filter>
    <path id="tear" d="${tear}"/>
    <mask id="cut">
      <rect width="1024" height="1024" fill="#fff"/>
      <use href="#tear" fill="#000"/>
    </mask>
    <clipPath id="tile"><rect x="80" y="80" width="864" height="864" rx="212"/></clipPath>
  </defs>
  <g clip-path="url(#tile)">
    <rect width="1024" height="1024" fill="#1C1016"/>
    <use href="#tear" fill="url(#light)" filter="url(#bloom)"/>
    <use href="#tear" fill="url(#light)"/>
    <g mask="url(#cut)">
      <rect width="1024" height="1024" fill="url(#slab)"/>
      <ellipse cx="512" cy="512" rx="250" ry="430" fill="url(#spill)"/>
    </g>
    <use href="#tear" fill="none" stroke="#FFD9A0" stroke-opacity="0.8" stroke-width="5" stroke-linejoin="round"/>
    <!-- hairline cracks run on to the tile's edges: it's split, not dented -->
    <path d="M528 80 V100 M512 926 L506 944" stroke="#FFB070" stroke-width="5" stroke-linecap="round"/>
  </g>
  <rect x="80" y="80" width="864" height="864" rx="212" fill="none" stroke="#fff" stroke-opacity="0.07" stroke-width="6"/>
</svg>
`;

// Silhouette: the tile with the tear cut out, for template/monochrome use.
const mono = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024">
  <defs>
    <mask id="cut"><rect width="1024" height="1024" fill="#fff"/><path d="${tear}" fill="#000" transform="translate(512 512) scale(1.25 1) translate(-512 -512)"/></mask>
  </defs>
  <rect x="80" y="80" width="864" height="864" rx="212" fill="#000" mask="url(#cut)"/>
</svg>
`;

writeFileSync(join(here, 'logo.svg'), logo);
writeFileSync(join(here, 'logo-mono.svg'), mono);
console.log('wrote brand/logo.svg, brand/logo-mono.svg');
